### ISSUE TITLE
Failure to run the website locally due to invalid content in webpack.base.config

### ISSUE THREAD

**Issue by bernhard-hofmann** [Freegle/iznik-client#5]
Attempting to run the website locally using `npm run dev:fd` fails due to the ellipsis in `webpack.base.config`:

    D:\___\GitHub\Freegle\iznik-client\dev\webpack.base.config.js:39
                ...shims.aliases
                ^^^
    SyntaxError: Unexpected token ...
        at Object.exports.runInThisContext (vm.js:76:16)
        at Module._compile (module.js:545:28)

**Comment by edwh** [comment]
What version of npm are you using?  I saw this when using an old one, 
which is why on the home page it says you need >= v5.5.1.

------ Original Message ------

**Comment by bernhard-hofmann** [comment]
npm -v
    5.6.0

**Comment by edwh** [comment]
Maybe the version of babel, then.  I assume if you'd messed with dependency version numbers you'd have mentioned it.

Do an npm ls and mail me the output, then I'll compare it to mine (I'm on Windows too).  @nicksellen recently installed fine, but he's on Linux, so perhaps there's a difference.

**Comment by edwh** [comment]
This is ES6 syntax, btw, so it's not invalid, just advanced.

**Comment by bernhard-hofmann** [comment]
I see. I don't have your email address. The `npm ls` output is rather lengthy, but here's my `babel` "section":

```
+-- babel-core@6.26.0
| +-- babel-code-frame@6.26.0
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- escape-string-regexp@1.0.5 deduped
| | | +-- has-ansi@2.0.0 deduped
| | | +-- strip-ansi@3.0.1 deduped
| | | `-- supports-color@2.0.0
| | +-- esutils@2.0.2 deduped
| | `-- js-tokens@3.0.2
| +-- babel-generator@6.26.0
| | +-- babel-messages@6.23.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | +-- babel-types@6.26.0 deduped
| | +-- detect-indent@4.0.0
| | | `-- repeating@2.0.1
| | |   `-- is-finite@1.0.2 deduped
| | +-- jsesc@1.3.0
| | +-- lodash@4.17.4 deduped
| | +-- source-map@0.5.7 deduped
| | `-- trim-right@1.0.1
| +-- babel-helpers@6.24.1
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-template@6.26.0 deduped
| +-- babel-messages@6.23.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-register@6.26.0
| | +-- babel-core@6.26.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | +-- core-js@2.5.1 deduped
| | +-- home-or-tmp@2.0.0
| | | +-- os-homedir@1.0.2 deduped
| | | `-- os-tmpdir@1.0.2 deduped
| | +-- lodash@4.17.4 deduped
| | +-- mkdirp@0.5.1 deduped
| | `-- source-map-support@0.4.18 deduped
| +-- babel-runtime@6.26.0 deduped
| +-- babel-template@6.26.0
| | +-- babel-runtime@6.26.0 deduped
| | +-- babel-traverse@6.26.0 deduped
| | +-- babel-types@6.26.0 deduped
| | +-- babylon@6.18.0 deduped
| | `-- lodash@4.17.4 deduped
| +-- babel-traverse@6.26.0
| | +-- babel-code-frame@6.26.0 deduped
| | +-- babel-messages@6.23.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | +-- babel-types@6.26.0 deduped
| | +-- babylon@6.18.0 deduped
| | +-- debug@2.6.9 deduped
| | +-- globals@9.18.0
| | +-- invariant@2.2.2 deduped
| | `-- lodash@4.17.4 deduped
| +-- babel-types@6.26.0
| | +-- babel-runtime@6.26.0 deduped
| | +-- esutils@2.0.2 deduped
| | +-- lodash@4.17.4 deduped
| | `-- to-fast-properties@1.0.3
| +-- babylon@6.18.0
| +-- convert-source-map@1.5.0
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- json5@0.5.1
| +-- lodash@4.17.4
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.8
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- path-is-absolute@1.0.1
| +-- private@0.1.8
| +-- slash@1.0.0
| `-- source-map@0.5.7
+-- babel-eslint@8.2.1
| +-- @babel/code-frame@7.0.0-beta.36
| | +-- chalk@2.3.0 deduped
| | +-- esutils@2.0.2 deduped
| | `-- js-tokens@3.0.2 deduped
| +-- @babel/traverse@7.0.0-beta.36
| | +-- @babel/code-frame@7.0.0-beta.36 deduped
| | +-- @babel/helper-function-name@7.0.0-beta.36
| | | +-- @babel/helper-get-function-arity@7.0.0-beta.36
| | | | `-- @babel/types@7.0.0-beta.36 deduped
| | | +-- @babel/template@7.0.0-beta.36
| | | | +-- @babel/code-frame@7.0.0-beta.36 deduped
| | | | +-- @babel/types@7.0.0-beta.36 deduped
| | | | +-- babylon@7.0.0-beta.36
| | | | `-- lodash@4.17.4 deduped
| | | `-- @babel/types@7.0.0-beta.36 deduped
| | +-- @babel/types@7.0.0-beta.36 deduped
| | +-- babylon@7.0.0-beta.36
| | +-- debug@3.1.0
| | | `-- ms@2.0.0 deduped
| | +-- globals@11.2.0
| | +-- invariant@2.2.2 deduped
| | `-- lodash@4.17.4 deduped
| +-- @babel/types@7.0.0-beta.36
| | +-- esutils@2.0.2 deduped
| | +-- lodash@4.17.4 deduped
| | `-- to-fast-properties@2.0.0
| +-- babylon@7.0.0-beta.36
| +-- eslint-scope@3.7.1
| | +-- esrecurse@4.2.0
| | | +-- estraverse@4.2.0 deduped
| | | `-- object-assign@4.1.1 deduped
| | `-- estraverse@4.2.0
| `-- eslint-visitor-keys@1.0.0
+-- babel-jest@22.1.0
| +-- babel-plugin-istanbul@4.1.5
| | +-- find-up@2.1.0
| | | `-- locate-path@2.0.0
| | |   +-- p-locate@2.0.0
| | |   | `-- p-limit@1.1.0 deduped
| | |   `-- path-exists@3.0.0
| | +-- istanbul-lib-instrument@1.9.1
| | | +-- babel-generator@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | +-- babel-types@6.26.0 deduped
| | | +-- babylon@6.18.0 deduped
| | | +-- istanbul-lib-coverage@1.1.1 deduped
| | | `-- semver@5.4.1 deduped
| | `-- test-exclude@4.1.1
| |   +-- arrify@1.0.1 deduped
| |   +-- micromatch@2.3.11 deduped
| |   +-- object-assign@4.1.1 deduped
| |   +-- read-pkg-up@1.0.1
| |   | +-- find-up@1.1.2
| |   | | +-- path-exists@2.1.0
| |   | | | `-- pinkie-promise@2.0.1 deduped
| |   | | `-- pinkie-promise@2.0.1 deduped
| |   | `-- read-pkg@1.1.0
| |   |   +-- load-json-file@1.1.0
| |   |   | +-- graceful-fs@4.1.11 deduped
| |   |   | +-- parse-json@2.2.0 deduped
| |   |   | +-- pify@2.3.0 deduped
| |   |   | +-- pinkie-promise@2.0.1 deduped
| |   |   | `-- strip-bom@2.0.0
| |   |   |   `-- is-utf8@0.2.1 deduped
| |   |   +-- normalize-package-data@2.4.0 deduped
| |   |   `-- path-type@1.1.0
| |   |     +-- graceful-fs@4.1.11 deduped
| |   |     +-- pify@2.3.0 deduped
| |   |     `-- pinkie-promise@2.0.1 deduped
| |   `-- require-main-filename@1.0.1 deduped
| `-- babel-preset-jest@22.1.0
|   +-- babel-plugin-jest-hoist@22.1.0
|   `-- babel-plugin-syntax-object-rest-spread@6.13.0
+-- babel-loader@7.1.2
| +-- find-cache-dir@1.0.0
| | +-- commondir@1.0.1
| | +-- make-dir@1.1.0
| | | `-- pify@3.0.0
| | `-- pkg-dir@2.0.0
| |   `-- find-up@2.1.0 deduped
| +-- loader-utils@1.1.0
| | +-- big.js@3.2.0
| | +-- emojis-list@2.1.0
| | `-- json5@0.5.1 deduped
| `-- mkdirp@0.5.1 deduped
+-- babel-plugin-syntax-dynamic-import@6.18.0
+-- babel-preset-env@1.6.1
| +-- babel-plugin-check-es2015-constants@6.22.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-syntax-trailing-function-commas@6.22.0
| +-- babel-plugin-transform-async-to-generator@6.24.1
| | +-- babel-helper-remap-async-to-generator@6.24.1
| | | +-- babel-helper-function-name@6.24.1 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-syntax-async-functions@6.13.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-arrow-functions@6.22.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-block-scoped-functions@6.22.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-block-scoping@6.26.0
| | +-- babel-runtime@6.26.0 deduped
| | +-- babel-template@6.26.0 deduped
| | +-- babel-traverse@6.26.0 deduped
| | +-- babel-types@6.26.0 deduped
| | `-- lodash@4.17.4 deduped
| +-- babel-plugin-transform-es2015-classes@6.24.1
| | +-- babel-helper-define-map@6.26.0
| | | +-- babel-helper-function-name@6.24.1 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-types@6.26.0 deduped
| | | `-- lodash@4.17.4 deduped
| | +-- babel-helper-function-name@6.24.1
| | | +-- babel-helper-get-function-arity@6.24.1 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-helper-optimise-call-expression@6.24.1
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-helper-replace-supers@6.24.1
| | | +-- babel-helper-optimise-call-expression@6.24.1 deduped
| | | +-- babel-messages@6.23.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-template@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-messages@6.23.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | +-- babel-template@6.26.0 deduped
| | +-- babel-traverse@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-transform-es2015-computed-properties@6.24.1
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-template@6.26.0 deduped
| +-- babel-plugin-transform-es2015-destructuring@6.23.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-duplicate-keys@6.24.1
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-transform-es2015-for-of@6.23.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-function-name@6.24.1
| | +-- babel-helper-function-name@6.24.1 deduped
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-transform-es2015-literals@6.22.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-modules-amd@6.24.1
| | +-- babel-plugin-transform-es2015-modules-commonjs@6.26.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-template@6.26.0 deduped
| +-- babel-plugin-transform-es2015-modules-commonjs@6.26.0
| | +-- babel-plugin-transform-strict-mode@6.24.1
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | +-- babel-template@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-transform-es2015-modules-systemjs@6.24.1
| | +-- babel-helper-hoist-variables@6.24.1
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-template@6.26.0 deduped
| +-- babel-plugin-transform-es2015-modules-umd@6.24.1
| | +-- babel-plugin-transform-es2015-modules-amd@6.24.1 deduped
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-template@6.26.0 deduped
| +-- babel-plugin-transform-es2015-object-super@6.24.1
| | +-- babel-helper-replace-supers@6.24.1 deduped
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-parameters@6.24.1
| | +-- babel-helper-call-delegate@6.24.1
| | | +-- babel-helper-hoist-variables@6.24.1 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-traverse@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-helper-get-function-arity@6.24.1
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | +-- babel-template@6.26.0 deduped
| | +-- babel-traverse@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-transform-es2015-shorthand-properties@6.24.1
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-transform-es2015-spread@6.22.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-sticky-regex@6.24.1
| | +-- babel-helper-regex@6.26.0
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-types@6.26.0 deduped
| | | `-- lodash@4.17.4 deduped
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-transform-es2015-template-literals@6.22.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-typeof-symbol@6.23.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-es2015-unicode-regex@6.24.1
| | +-- babel-helper-regex@6.26.0 deduped
| | +-- babel-runtime@6.26.0 deduped
| | `-- regexpu-core@2.0.0
| |   +-- regenerate@1.3.3
| |   +-- regjsgen@0.2.0
| |   `-- regjsparser@0.1.5
| |     `-- jsesc@0.5.0
| +-- babel-plugin-transform-exponentiation-operator@6.24.1
| | +-- babel-helper-builder-binary-assignment-operator-visitor@6.24.1
| | | +-- babel-helper-explode-assignable-expression@6.24.1
| | | | +-- babel-runtime@6.26.0 deduped
| | | | +-- babel-traverse@6.26.0 deduped
| | | | `-- babel-types@6.26.0 deduped
| | | +-- babel-runtime@6.26.0 deduped
| | | `-- babel-types@6.26.0 deduped
| | +-- babel-plugin-syntax-exponentiation-operator@6.13.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-regenerator@6.26.0
| | `-- regenerator-transform@0.10.1
| |   +-- babel-runtime@6.26.0 deduped
| |   +-- babel-types@6.26.0 deduped
| |   `-- private@0.1.8 deduped
| +-- browserslist@2.9.0
| | +-- caniuse-lite@1.0.30000769
| | `-- electron-to-chromium@1.3.27
| +-- invariant@2.2.2
| | `-- loose-envify@1.3.1 deduped
| `-- semver@5.4.1
+-- babel-preset-react-app@3.1.1
| +-- babel-plugin-dynamic-import-node@1.1.0
| | +-- babel-plugin-syntax-dynamic-import@6.18.0 deduped
| | +-- babel-template@6.26.0 deduped
| | `-- babel-types@6.26.0 deduped
| +-- babel-plugin-syntax-dynamic-import@6.18.0 deduped
| +-- babel-plugin-transform-class-properties@6.24.1
| | +-- babel-helper-function-name@6.24.1 deduped
| | +-- babel-plugin-syntax-class-properties@6.13.0
| | +-- babel-runtime@6.26.0 deduped
| | `-- babel-template@6.26.0 deduped
| +-- babel-plugin-transform-es2015-destructuring@6.23.0 deduped
| +-- babel-plugin-transform-object-rest-spread@6.26.0
| | +-- babel-plugin-syntax-object-rest-spread@6.13.0 deduped
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-react-constant-elements@6.23.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-react-jsx@6.24.1
| | +-- babel-helper-builder-react-jsx@6.26.0
| | | +-- babel-runtime@6.26.0 deduped
| | | +-- babel-types@6.26.0 deduped
| | | `-- esutils@2.0.2 deduped
| | +-- babel-plugin-syntax-jsx@6.18.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-react-jsx-self@6.22.0
| | +-- babel-plugin-syntax-jsx@6.18.0 deduped
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-react-jsx-source@6.22.0
| | +-- babel-plugin-syntax-jsx@6.18.0 deduped
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-plugin-transform-regenerator@6.26.0 deduped
| +-- babel-plugin-transform-runtime@6.23.0
| | `-- babel-runtime@6.26.0 deduped
| +-- babel-preset-env@1.6.1 deduped
| `-- babel-preset-react@6.24.1
|   +-- babel-plugin-syntax-jsx@6.18.0 deduped
|   +-- babel-plugin-transform-react-display-name@6.25.0
|   | `-- babel-runtime@6.26.0 deduped
|   +-- babel-plugin-transform-react-jsx@6.24.1 deduped
|   +-- babel-plugin-transform-react-jsx-self@6.22.0 deduped
|   +-- babel-plugin-transform-react-jsx-source@6.22.0 deduped
|   `-- babel-preset-flow@6.23.0 deduped
+-- babel-runtime@6.26.0
| +-- core-js@2.5.1
| `-- regenerator-runtime@0.11.0
```

**Comment by bernhard-hofmann** [comment]
Currently running `npm update` - what's the worst that can happen. ^^

**Comment by edwh** [comment]
I've mailed you.

**Comment by bernhard-hofmann** [comment]
Seems the cause of this was either an out of date npm package, or, more likely, an old Node version. I had 7.0.0 and upgraded to 8.9.4 which resolved the issue.

**Comment by edwh** [comment]
I've updated the readme to say we need a later node.

------ Original Message ------
